// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	contractclient "job4j.ru/share-trip/internal/clients/contract"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CheckService provides a mock function with given fields: ctx, companyID, serviceCode
func (_m *Client) CheckService(ctx context.Context, companyID string, serviceCode string) (contractclient.CheckResult, error) {
	ret := _m.Called(ctx, companyID, serviceCode)

	if len(ret) == 0 {
		panic("no return value specified for CheckService")
	}

	var r0 contractclient.CheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (contractclient.CheckResult, error)); ok {
		return rf(ctx, companyID, serviceCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) contractclient.CheckResult); ok {
		r0 = rf(ctx, companyID, serviceCode)
	} else {
		r0 = ret.Get(0).(contractclient.CheckResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, companyID, serviceCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
